class UsageError(Exception):
    pass


class UrlError(Exception):
    pass